"""Human-readable domain vocabulary used by the backend."""

DOMAIN_VOCABULARY = {
    "Organization": "Tenant boundary that owns users, templates, jobs, artifacts, and audit logs.",
    "User": "Organization member who uploads templates or triggers generation.",
    "Template": "Logical document blueprint such as a certificate or transcript.",
    "TemplateVersion": "Versioned source file and extracted schema snapshot for a template.",
    "DocumentJob": "Asynchronous request to render a document from a template version.",
    "DocumentArtifact": "Stored output file such as DOCX, PDF, or preview generated by a job.",
    "AuditLog": "Immutable event trail for operational and compliance-sensitive actions.",
}
